# Generated by Django 4.2.26 on 2025-11-23 00:39

from django.db import migrations, models
import django.db.models.deletion
import guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('nb_mairie', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de personnes à la mairie')),
                ('nb_soiree', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de personnes à la soirée')),
                ('is_attending', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('is_attending', models.BooleanField(default=None, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.party')),
            ],
        ),
    ]
