# Generated by Django 4.2.26 on 2025-11-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
