# Generated by Django 4.2.26 on 2025-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='nb_mairie',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de personnes à la mairie'),
        ),
        migrations.AddField(
            model_name='party',
            name='nb_soiree',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de personnes à la soirée'),
        ),
    ]
