# Generated by Django 4.2.26 on 2025-11-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_party_nb_mairie_party_nb_soiree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='party',
            name='category',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_sent',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rehearsal_dinner',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_sent',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
    ]
